[workspace]
members = ["crates/avian2d", "crates/avian3d"]
resolver = "2"

[profile.dev]
opt-level = 1 # Use slightly better optimization, so examples work

[patch.crates-io]
bevy = {git = "https://github.com/bevyengine/bevy"}
bevy_math = {git = "https://github.com/bevyengine/bevy"}
bevy_reflect = {git = "https://github.com/bevyengine/bevy"}
bevy_heavy = {git = "https://github.com/NiseVoid/bevy_heavy", branch="no_std"}
bevy_transform_interpolation = {git = "https://github.com/NiseVoid/bevy_transform_interpolation"}
